services:
  - type: web
    name: shl-recommender
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python startup.py
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_MODEL
        value: gpt-4o
    healthCheckPath: /health
    autoDeploy: true
